### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by PatchLion** [opendarkeden/server#1]
现在还在研究这个服务端吗？

**Comment by hillwah** [comment]
客户端对不上，没有研究了。

**Comment by PatchLion** [comment]
网上能找到服务端和客户端在一个压缩包的资源，但是不知道那个能不能对上

**Comment by hillwah** [comment]
我们也试过好几个，好像都不行吧，太久给忘记了。
也有客户端的部分源码，但是编译后不能用，应该还少很多东西，就没有再玩了。
你可以试试，网上有很多残缺的东西。

**Comment by PatchLion** [comment]
好吧~

**Comment by tiancaiamao** [comment]
好啦，现在终于有一个可用的服务端 + 客户端了 
@PatchLion  @hillwah
