### ISSUE TITLE
login problem error

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#10]
![image](https://user-images.githubusercontent.com/84734363/123469537-787a9200-d5f3-11eb-9ada-b826bf98085b.png)

**Comment by tiancaiamao** [comment]
It says Incorrect DATE value: '0000-00-00'.
Make sure the `sql_mode` allow zero date time, remove the `NO_ZERO_DATE` from the `sql_mode`:

```
mysql> select @@global.sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@global.sql_mode                                                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> set @@global.sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
Query OK, 0 rows affected (0.02 sec)
```

**Comment by tiancaiamao** [comment]
See https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

**Comment by tiancaiamao** [comment]
Does it solve your problem? @Supacek

**Comment by Supacek** [comment]
i have that 0000-00-00 in tables but also i try to change it to 2020-01-01 but no work

**Comment by Supacek** [comment]
i got it but got somethink new..InvalidProtocolException : invalid packet id(162)
 virtual void LoginPlayer::processCommand(bool)
  std::string PacketFactoryManager::getPacketName(PacketID_t)

**Comment by tiancaiamao** [comment]
> i got it but got somethink new..InvalidProtocolException : invalid packet id(162)
> virtual void LoginPlayer::processCommand(bool)
> std::string PacketFactoryManager::getPacketName(PacketID_t)


The server and the client must match, otherwise that error appears.
You can check the `client/.../Packet.h` and `server/.../Packet.h`

https://github.com/opendarkeden/server/blob/master/src/Core/Packet.h#L717
https://github.com/opendarkeden/client/blob/master/Client/Packet/Packet.h#L227

@Supacek
