### ISSUE TITLE
Party no working 

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#101]
![image](https://user-images.githubusercontent.com/84734363/202908541-64de8a2a-8f8d-403e-b2cd-b116de67ae1c.png)
Party no working 
After Invite DC

**Comment by Supacek** [comment]
i test change those files and still no any error nothing 
![image](https://user-images.githubusercontent.com/84734363/202915018-7f28094d-06e4-4609-854b-16e8fd4f3c38.png)

**Comment by de702** [comment]
I believe this has been fixed already

**Comment by Supacek** [comment]
> I believe this has been fixed already

but its not working :/ weird

**Comment by Supacek** [comment]
how i can fix that i dont even have any log file or something from gameserver loginserver or sharedserver log but theres nothink its empty after hit invite just have DC :/

**Comment by de702** [comment]
https://github.com/opendarkeden/server/issues/75

**Comment by Supacek** [comment]
can anyone test it ?

**Comment by de702** [comment]
I did wasn't no error either that fixed my DC problem with party.....

**Comment by Supacek** [comment]
> with p

what u mean ?

**Comment by Supacek** [comment]
i have exact same src and its no working no errors only DC

**Comment by Supacek** [comment]
soo its working problz it has problem with Gm account sometime its weir like i log in 2 accounts i get party and after i change file i was thinking  its was it but it didnt and i come back to original mz files and i get long time dc and now i dont have dc thats weir it must be somethink with UserIpInfo table also but now i can get partz and no dc and i did nothink thats weird..

**Comment by Supacek** [comment]
OK i know where is problem
 in Keyboard language !!! when i press Alt+Shift and i swap my Lang in windows its doing same think when u presing alt and clicking NPC and u have DC!!!

**Comment by Supacek** [comment]
so we need fix the Keyboard problem :(

**Comment by Supacek** [comment]
#91

**Comment by tiancaiamao** [comment]
This issue is duplicated by https://github.com/opendarkeden/server/issues/75
