### ISSUE TITLE
Drop Ratio

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#105]
![image](https://user-images.githubusercontent.com/84734363/204155282-5752d537-2407-4320-bb70-e2f638798fab.png)
 like im moving with the ratio up and dont and im geting only White items sometime yellow or 2op   its working difrent then other servers or i dont know.... any idea? someone test it ?

**Comment by tiancaiamao** [comment]
Drop ratio can be controled by GM command?

https://github.com/opendarkeden/server/blob/1361037a54177758e08cf3c81305eafa3a966c76/src/Core/CGSayHandler.cpp#L1208-L1670

**Comment by Supacek** [comment]
of u can yes  but looks like nothink change :/

**Comment by Supacek** [comment]
its was my problem theres no problem :D sorry
