### ISSUE TITLE
its not working did u test it ? it create guild after restart but its not working normaly theres no message nothink

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#111]
its not working did u test it ? it create guild after restart but its not working normaly theres no message nothink

_Originally posted by @Supacek in https://github.com/opendarkeden/server/issues/97#issuecomment-1347954565_

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/207276443-ade2e16c-21a1-4da2-80e0-6aaa7f12bb6c.png)

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/207283199-0477ebd4-b682-4d62-b637-ed0b7da882ee.png)

**Comment by Supacek** [comment]
when i change  it like before it was working but i redownload ur changes and its not working

**Comment by Supacek** [comment]
i added the intro into that shared file Guild.cpp
"INSERT INTO GuildMember( GuildID, Name, `Rank`, Intro  ) VALUES ( %d, '%s', %d, 1 )",

**Comment by Supacek** [comment]
and its working now but idk what happened when player put somethink in intro... there must be more testing

**Comment by Supacek** [comment]
we should make just One mysql version and not  5 and 8

**Comment by tiancaiamao** [comment]
OK, I see. Thanks for your feedback.  @Supacek 

This can be fixed by removing the `STRICT_TRANS_TABLES` from the sql_mode:

```
mysql> select @@global.sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@global.sql_mode                                                                                                     |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

I'll update here.
