### ISSUE TITLE
Guild chat no work

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#119]
didnt work ? did we fix it or not?

**Comment by tiancaiamao** [comment]
I'm not sure ... there is a bug of party chat which has been fixed https://github.com/opendarkeden/client/issues/35
But I haven't test guild chat yet.

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/209328746-bb53452f-5d58-4402-a23a-07ef827b6e86.png)

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/209328830-5d8f761e-d623-4673-832f-5ee6f9da3dbf.png)

**Comment by Supacek** [comment]
thats shoting at me when typing in guild chat :D

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/209853334-7c2e9003-e27e-4d10-b3b4-f539e442ba50.png)
nothink else just  invalid packet ID

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/210182362-74186416-d8d0-48dc-964b-69ef61628c29.png)
but after make 
![image](https://user-images.githubusercontent.com/84734363/210182369-f7d4954d-dd9c-4e41-8215-5dfd38e1ef65.png)

**Comment by Supacek** [comment]
guild mark can by fixed using any other   Horn.inf and guildmark.inf file from another clients.   Guild chat needs to be fixed..

**Comment by Supacek** [comment]
anyone check this problem?  its kinda importent to fix guild chat players rly need that :( anyone can help eith that guild chat problems guys any steps?

**Comment by Supacek** [comment]
@tiancaiamao   hallo sir do u think u can look at this guild chat problem please ?  im kinda lost in this packet problem... i need kick xD

**Comment by Supacek** [comment]
Someone can help here ?  :-) or anyone who has working guild chat in v2 can share some files that would help me to fix the guild chat?? il be thanx To you guys

**Comment by Supacek** [comment]
We need fix the  
![image](https://user-images.githubusercontent.com/84734363/216686972-03ecb464-e520-4caf-84d9-15eb638cddf3.png)

GGGuildChatFactory we need that for guildchat

**Comment by Supacek** [comment]
if u reffer it from other server its look like this 
![image](https://user-images.githubusercontent.com/84734363/216687169-5c7022ae-aca1-42d7-97f1-f330c5f6c2a7.png)
so i make copy and put just 
![image](https://user-images.githubusercontent.com/84734363/216687193-73a2b8ae-5567-44d6-9332-4d1efce9d082.png)
but then we have error 
![image](https://user-images.githubusercontent.com/84734363/216687301-fd4bce00-62a8-4fc2-a733-fd3c8a413b25.png)

**Comment by Supacek** [comment]
@tiancaiamao  can u help ?

**Comment by Supacek** [comment]
also in client src its same like this 
![image](https://user-images.githubusercontent.com/84734363/216724446-f41ba92d-29fb-4235-a21c-d99f9ccb9169.png)

**Comment by Supacek** [comment]
hm still nothink new but when i add  addFactory( new GGGuildChatFactory());  under 
![image](https://user-images.githubusercontent.com/84734363/218279288-baba0a9a-9f9c-477c-a86a-de6a6f2e0b05.png)
 then i can compile the server but when i type ingame then we have  
 
![image](https://user-images.githubusercontent.com/84734363/218279314-8c93b5b7-ee82-46a0-9630-30f0e7185ee6.png)
