### ISSUE TITLE
error when I start gameserver

### ISSUE THREAD

**Issue by K-UseBy** [opendarkeden/server#12]
![issue2](https://user-images.githubusercontent.com/49011864/123803497-4fc20780-d927-11eb-902e-870293c2f670.PNG)
when I enter './bin/gameserver -f ./conf/gameserver.conf' to start gameserver.
it seems like it can't load libxerces-c-3.2.so file.
what can i do?

**Comment by tiancaiamao** [comment]
What's your ubuntu version? 

```
genius@genius-System-Product-Name:~/project/opendarkeden/server/src/server$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

Do you get xerces-c lib by `sudo apt install libxerces-c-dev`, or you manually specify the `LIBRARY_PATH`?
If you installing using apt,  libxerces-c-3.2.so should be in the standard path.

If you set `LIBRARY_PATH`, maybe you need to set `LD_LIBRARY_PATH` to include the path

```
export LD_LIBRARY_PATH = /dir/path/of/the/libxerces:$LD_LIBRARY_PATH
```

And you can try `ldconfig -v` to find the path of libxerces-c-3.2.so file

```
genius@genius-System-Product-Name:~/project/opendarkeden/server/src/server$ ldconfig -v |grep xerces-c
/sbin/ldconfig.real: 无法对 /usr/local/lib/x86_64-linux-gnu 进行 stat 操作: 没有那个文件或目录
/sbin/ldconfig.real: 多次给出路径“/usr/lib/x86_64-linux-gnu”
/sbin/ldconfig.real: 多次给出路径“/lib/x86_64-linux-gnu”
/sbin/ldconfig.real: 多次给出路径“/usr/lib/x86_64-linux-gnu”
/sbin/ldconfig.real: 多次给出路径“/usr/lib”
	libxerces-c-3.2.so -> libxerces-c.so
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.31.so is the dynamic linker, ignoring
```

It's `/lib/x86_64-linux-gnu/libxerces-c.so` in my ubuntu environment.

**Comment by K-UseBy** [comment]
solved it
but another problem exist...
https://github.com/opendarkeden/server/issues/13
