### ISSUE TITLE
Problem in load the SQL file

### ISSUE THREAD

**Issue by K-UseBy** [opendarkeden/server#13]
When i load the SQL files to mysql.
![issue1](https://user-images.githubusercontent.com/49011864/123970504-1d321080-d9f4-11eb-94cf-ef8464cc685a.PNG)
![issue2](https://user-images.githubusercontent.com/49011864/123970512-1e633d80-d9f4-11eb-9352-400ea7db2273.PNG)
![issue3](https://user-images.githubusercontent.com/49011864/123970518-20c59780-d9f4-11eb-89c1-d4b4b68acdb0.PNG)

it doesn't work with error like this

**Comment by tiancaiamao** [comment]
Duplicated with #5 

Hey buddy, you need to follow README.md file, set the sql_mode without `no_zero_date`
