### ISSUE TITLE
The player role can't move if they login to server1

### ISSUE THREAD

**Issue by tiancaiamao** [opendarkeden/server#19]
From [here](https://github.com/opendarkeden/docs/blob/master/howto/8.%E4%BA%BA%E7%89%A9%E5%8D%A1%E5%9B%BE%E7%9A%84%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95.txt):

> 
> 这个问题已经问了3天了，没人理我！新建的人物进游戏后，就卡在地图里！不管是鬼还是人还是魔灵都一样，动不了，身上的装备也不能丢，服务端给的2个账号里的人物可以走动，装备在装备栏里的东西都是红色的！！！不能打怪也用不了技能！
> 
> 
> 新建账号 要在player里 把账号 CurrentServerGroupID  改成1  ---(卡图就是因为CurrentServerGroupID这个是0)         111111和222222 里角色可以删除 在人slayer 鬼vampire 魔ousters表里  里面删除后从建角色即可gm权限根据种族在种族表里改把人slayer 鬼vampire 魔ousters三个表里的   competence  改成0
> 

It says change the `CurrentServerGroupID` of the player table rows to 1 if it's 0 ...

This might be the problem, I'm not sure ... I need to figure it out.

@Chrius @xDezossAx

**Comment by Chrius** [comment]
I tried doing this, first time I tried making anew account and changing this before creating a character and the second after.
Both times I wasn't able to move.

Also it seems that if you don't change this, the server automatically changes it after you enter the first group.

The weird thing is I tried logging in to a human, I was at the respawn point in the base, and I can move once, but regardless of direction, I get teleported to the top-left of the base and get stuck on the map. 
It's as if for some reason the pathing on this server is borked... 
No idea where the server gets the map info from though.
