### ISSUE TITLE
upgrade the lua library to the latest

### ISSUE THREAD

**Issue by tiancaiamao** [opendarkeden/server#2]
This project is still using the lua 4.0.1, it's pretty outdated.
It's better to upgrade to the latest one.

**Comment by tiancaiamao** [comment]
![图片](https://user-images.githubusercontent.com/1420062/121156821-a0d86180-c87b-11eb-9b41-4d75940f2d88.png)

**Comment by Supacek** [comment]
updated  5.1
[LuaState.cpp.txt](https://github.com/opendarkeden/server/files/9905542/LuaState.cpp.txt)
[LuaState.h.txt](https://github.com/opendarkeden/server/files/9905543/LuaState.h.txt)

**Comment by Supacek** [comment]
Updated lua calls so that it now uses lua 5.1
Fixed the lua includes in order for it to build correctly

**Comment by tiancaiamao** [comment]
Amazing work! @Supacek 
I'll take a look when free
