### ISSUE TITLE
No NPC in the map

### ISSUE THREAD

**Issue by tiancaiamao** [opendarkeden/server#21]
I need to figure out why ...

**Comment by xDezossAx** [comment]
> I need to figure out why ...

And because the Name column of the NPC table does not match an NPC column of the Triggers table, they must have the same name, the Triggers and where it informs the NPC position, and as other options, I put the Triggers and Server NPC table RedHat classic and it worked :)

**Comment by tiancaiamao** [comment]
OK ...I'm try to change the Triggers table into UTF8 ...
And then this error happened:

```
@@@@@@@@@@@@@@@ [1501]th ZONE INITIALIZATION START @@@@@@@@@@@@@@@
NPC[奥塔乌斯分身1] loading begin >> loading end
NPC[苛鸥何胶档快固2] loading begin >> InvalidProtocolException : too large name length
 void Zone::addCreature(Creature*, ZoneCoord_t, ZoneCoord_t, Dir_t)
  void Zone::broadcastPacket(ZoneCoord_t, ZoneCoord_t, Packet*, Creature*, bool, Range_t)
   virtual void GCAddNPC::write(SocketOutputStream&) const

InvalidProtocolException : too large name length
 void NPC::init()
  virtual bool NPC::load()
   bool Trigger::activate(Creature*, Creature*) const
    virtual void ActionSetPosition::execute(Creature*, Creature*)
     void Zone::addCreature(Creature*, ZoneCoord_t, ZoneCoord_t, Dir_t)
      void Zone::broadcastPacket(ZoneCoord_t, ZoneCoord_t, Packet*, Creature*, bool, Range_t)
       virtual void GCAddNPC::write(SocketOutputStream&) const

InvalidProtocolException : too large name length
 void NPCManager::load(ZoneID_t, int)
  void NPC::init()
   virtual bool NPC::load()
    bool Trigger::activate(Creature*, Creature*) const
     virtual void ActionSetPosition::execute(Creature*, Creature*)
      void Zone::addCreature(Creature*, ZoneCoord_t, ZoneCoord_t, Dir_t)
       void Zone::broadcastPacket(ZoneCoord_t, ZoneCoord_t, Packet*, Creature*, bool, Range_t)
        virtual void GCAddNPC::write(SocketOutputStream&) const

AssertionError : 
Assertion Failed : Zone.cpp : 1660 : void Zone::load(bool)false at Sun Jul 11 10:33:51 2021


AssertionError : 
Assertion Failed : Zone.cpp : 1660 : void Zone::load(bool)false at Sun Jul 11 10:33:51 2021

 void Zone::init()
  void Zone::load(bool)

AssertionError : 
Assertion Failed : Zone.cpp : 1660 : void Zone::load(bool)false at Sun Jul 11 10:33:51 2021

 void ZoneGroupManager::init()
  void ZoneGroupManager::load()
   void Zone::init()
    void Zone::load(bool)

AssertionError : 
Assertion Failed : Zone.cpp : 1660 : void Zone::load(bool)false at Sun Jul 11 10:33:51 2021

 void GameServer::init()
  void ObjectManager::init()
   void ZoneGroupManager::init()
    void ZoneGroupManager::load()
     void Zone::init()
      void Zone::load(bool)

==============================================================================
UNHANDLED EXCEPTION OCCURED
==============================================================================
Aborted (core dumped)
```

It seems UTF8 character set costs more bytes than before, and the packet protocol had some constraint for the length.
Maybe I can change the limitation, but for both client and server ...
After that, it might be incompatible with other known client (I'm not sure)

Let me get a try.

**Comment by tiancaiamao** [comment]
[Triggers.txt](https://github.com/opendarkeden/server/files/6796269/Triggers.txt) For @Chrius if you're still online ... (I guess it's night in the US timezone)
Remember backup the old one, this is a try, you see the problem in the last comment.

**Comment by Chrius** [comment]
Dropped the old Triggers table and imported the new one, but still no npcs (I tested the Human area).

**Comment by Chrius** [comment]
@@@@@@@@@@@@@@@ [1501]th ZONE INITIALIZATION START @@@@@@@@@@@@@@@
NPC[奥塔乌斯分身1] loading begin >> loading end
NPC[苛鸥何胶档快固2] loading begin >> loading end

@@@@@@@@@@@@@@@ [1501]th ZONE INITIALIZATION SUCCESS @@@@@@@@@@@@@@@

Zone is loading apparently

**Comment by tiancaiamao** [comment]
I remove the check here https://github.com/opendarkeden/server/blob/master/src/Core/GCAddNPC.cpp#L31-L32 and here https://github.com/opendarkeden/server/blob/master/src/Core/GCAddNPC.cpp#L66-L67 and also update the client source code ...

The NPC shows ... but after that if I move to map 1506 (with a GM role), and walk to NPC, the server panic.

```
*warp 1506 200 72
```

So I have to fix that before I can file a PR  @Chrius

**Comment by tiancaiamao** [comment]
Done, please check the latest src and DARKEDEN.sql to see whether it works now @Chrius

**Comment by koreangang** [comment]
> I need to figure out why ...

hi tiancai can u tell me your discord

**Comment by Chrius** [comment]
Working now.
One interesting thing I noticed is that all of the NPC text is actually client based.
Using the built client their text is in korean (I think), on another old v2 client I have its in english.

**Comment by xDezossAx** [comment]
> Working now.
> One interesting thing I noticed is that all of the NPC text is actually client based.
> Using the built client their text is in korean (I think), on another old v2 client I have its in english.

Yes files NPC.inf and NPCScript.inf in cliente Data/Info :)

**Comment by tiancaiamao** [comment]
> > Working now.
> > One interesting thing I noticed is that all of the NPC text is actually client based.
> > Using the built client their text is in korean (I think), on another old v2 client I have its in english.
> 
> Yes files NPC.inf and NPCScript.inf in cliente Data/Info :)

It should be: https://github.com/opendarkeden/client/blob/master/Client/GameInitInfo.cpp#L778
But there is no NPC.inf in the Data/Info directory, I don't know how it works

**Comment by Chrius** [comment]
The file is hidden for some reason, but it's there.

**Comment by tiancaiamao** [comment]
> The file is hidden for some reason, but it's there.

Oh, I found it!

**Comment by tiancaiamao** [comment]
I still can't get it work.

This is the Korean version NPC.inf  NPCScript.inf
![image](https://user-images.githubusercontent.com/1420062/125219397-3fcb0000-e2f7-11eb-8e6f-b7ff3884ad49.png)

After replace them with a Chinese version NPC.inf NPCScript.inf
![捕获](https://user-images.githubusercontent.com/1420062/125219539-7ef95100-e2f7-11eb-8c50-4363e83e644d.PNG)


It's not Chinese character set
Maybe because of the file encoding

Have you tested the English NPC.inf, NPCScript.inf? @Chrius

**Comment by Chrius** [comment]
Yeah, they showed correctly but some dialog options weren't working on the NPC I tested.
[Info.zip](https://github.com/opendarkeden/server/files/6798158/Info.zip)

**Comment by tiancaiamao** [comment]
In that client, if I use Chinese character, it will be Chinese rendered as Korean ... so still a messy

**Comment by tiancaiamao** [comment]
> Yeah, they showed correctly but some dialog options weren't working on the NPC I tested.
> [Info.zip](https://github.com/opendarkeden/server/files/6798158/Info.zip)

English works! It's not affected by the encoding

**Comment by tiancaiamao** [comment]
> hi tiancai can u tell me your discord

@koreangang I'm considering it, but still not decided yet
Anyway, file an issue in github is welcomed, because other can see the discuss context too.

**Comment by tiancaiamao** [comment]
Fixed by https://github.com/opendarkeden/server/pull/22
