### ISSUE TITLE
Talking to NPC, click "I want to buy ..." option, the client panic

### ISSUE THREAD

**Issue by tiancaiamao** [opendarkeden/server#23]
This is caused by the packet size is not as expected.
When the database is translated to UTF8, it takes more bytes for some string.
And then the assumption for some packet max size doesn't hold any more.

There are two options to fix:
- change the database to latin1 and the client has their own (different) encoding
- change the database to utf8 and fix all the bugs

I'm not sure option 2 is a better choice. There maybe a lot of packet max size related errors.
But to support different languages, utf8 seems a big deal.

**Comment by tiancaiamao** [comment]
Do you meet this error? @Chrius

**Comment by tiancaiamao** [comment]
Just like this one, if option 2 is chosen, other client will be imcompatible with this server, because the server use UTF8 and the size of the packet is bigger than the client expected.
https://github.com/opendarkeden/client/pull/12

**Comment by tiancaiamao** [comment]
This kind of error ...  https://github.com/opendarkeden/server/issues/14#issuecomment-876831643
![](https://user-images.githubusercontent.com/51914495/125006788-50e4ea00-e035-11eb-85e2-fd0945ffcde1.png)

**Comment by xDezossAx** [comment]
> This is caused by the packet size is not as expected.
> When the database is translated to UTF8, it takes more bytes for some string.
> And then the assumption for some packet max size doesn't hold any more.
> 
> There are two options to fix:
> 
> * change the database to latin1 and the client has their own (different) encoding
> * change the database to utf8 and fix all the bugs
> 
> I'm not sure option 2 is a better choice. There maybe a lot of packet max size related errors.
> But to support different languages, utf8 seems a big deal.

hmm interesting, I'll do a test changing the database to latin1 and let me know if it worked... thanks for the tip! :)

**Comment by Chrius** [comment]
I didn't have much time to test this yesterday, but yeah, I'm getting the same error.

**Comment by tiancaiamao** [comment]
Now I have another idea.

Maybe I should use English and that avoid all the problems.
Either utf8 or latin1 is OK ... as long as Korean or Chinese is not used

**Comment by xDezossAx** [comment]
> Now I have another idea.
> 
> Maybe I should use English and that avoid all the problems.
> Either utf8 or latin1 is OK ... as long as Korean or Chinese is not used

Use english in the database example: name of triggers, npcs, shoptemplate?
I think I had already tried to translate at the bank... I'll try something again.

**Comment by tiancaiamao** [comment]
For example, the monster name have a `getHName` and `getEName` which means Korean and English respectably, we can always choose `getEName` ... @xDezossAx

**Comment by tiancaiamao** [comment]
This bug is fixed @xDezossAx @Chrius

**Comment by xDezossAx** [comment]
oh, very thankyou @tiancaiamao :D
