### ISSUE TITLE
MYSQL DB Import ERROR

### ISSUE THREAD

**Issue by chris5043** [opendarkeden/server#25]
![image](https://user-images.githubusercontent.com/16355753/126201955-c0ed5615-97b5-47a1-9b17-60d4833a7117.png)

**1231 - Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'**

How can I resolve this error?

**Comment by tiancaiamao** [comment]
Remove it...
Just remove `NO_ZERO_DATE` from the original sql_mode string.

**Comment by chris5043** [comment]
> Remove it...
> Just remove `NO_ZERO_DATE` from the original sql_mode string.

![image](https://user-images.githubusercontent.com/16355753/126283691-f35a7acc-7d63-409b-913e-b05aa0a9502e.png)
OK, Thx... I solved it this way.

_set @@global.sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';_

**Comment by chris5043** [comment]
![image](https://user-images.githubusercontent.com/16355753/126284423-b36c246f-2d25-4c6d-80af-38d4297c9a7c.png)

How do I solve this?

**Comment by tiancaiamao** [comment]
> How do I solve this?

You don't need to solve this...
I plan to use English Name in the future.
The Korean encoding cause too much trouble.

**Comment by chris5043** [comment]
Thanks
