### ISSUE TITLE
Transform Werwolf, bat, wolf vampire not found / teleport Sylph ouster not found

### ISSUE THREAD

**Issue by xDezossAx** [opendarkeden/server#29]
![image](https://user-images.githubusercontent.com/51914495/127939349-3eddd053-1b38-45d2-80df-966de7e8037e.png)

Apparently it's not a client bug because I tested it with 3 different ones, and on the server it doesn't give any error I also tried to change the bank to latin1 and it didn't work, right click on the head locks the char so giving *recall on it or trace to debug : s

**Comment by tiancaiamao** [comment]
Thanks for your report ... I will take a look this weekend.

**Comment by tiancaiamao** [comment]
Yes, I can reproduce the bug!

**Comment by xDezossAx** [comment]
Thank's @tiancaiamao ;), u very best!!
