### ISSUE TITLE
error while loading shared libraries: libmysqlclient.so.21

### ISSUE THREAD

**Issue by rafakave** [opendarkeden/server#42]
I'm trying to run binaries in a different environment (Ubuntu 14.0.4), with different versions of gcc (4.8.4) and I get the following error:

**ERROR**
`./gameserver: error while loading shared libraries: libmysqlclient.so.21: cannot open shared object file: No such file or directory`

Is it possible to run the compiled binaries in a different server?
Do you know how to bundle the required shared libraries into the final binary?
I ask because it makes more sense not to virtualize (dockerize) a native Linux server (although Docker makes it very easy the deployment in different servers).

**gcc -v**
```
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1\~14.04.4' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
```

**LSB_RELEASE -A**
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.6 LTS
Release:        14.04
Codename:       trusty
```

**Comment by xDezossAx** [comment]
Tenta copiar do diretorio /usr/lib/x86_64-linux-gnu/ do linux que você compilou, para o  Linux que você quer rodar, da um ldconfig e testa, acho que funciona, vou simular em casa e te aviso, e tipo o libstdc++glibc que o daemonctl pede, se copiar de um linux pra outro funfa.

**Comment by tiancaiamao** [comment]
> Is it possible to run the compiled binaries in a different server?

Sure... but ubuntu 14.04 is too old.
You can compile it on a native Linux server as long as you solve the library dependency here https://github.com/opendarkeden/server#dependency

I still recommend the newer ubuntu, it's handy and avoid a lot of troubles.

**Comment by rafakave** [comment]
> > Is it possible to run the compiled binaries in a different server?
> 
> Sure... but ubuntu 14.04 is too old.
> You can compile it on a native Linux server as long as you solve the library dependency here https://github.com/opendarkeden/server#dependency
> 
> I still recommend the newer ubuntu, it's handy and avoid a lot of troubles.

What about bundling the required libraries into the binary? So it can work in any distribution, at any version?

**Comment by tiancaiamao** [comment]
> > > Is it possible to run the compiled binaries in a different server?
> > 
> > 
> > Sure... but ubuntu 14.04 is too old.
> > You can compile it on a native Linux server as long as you solve the library dependency here https://github.com/opendarkeden/server#dependency
> > I still recommend the newer ubuntu, it's handy and avoid a lot of troubles.
> 
> What about bundling the required libraries into the binary? So it can work in any distribution, at any version?

This is what docker intend to be

**Comment by tiancaiamao** [comment]
I think this is resolved by using docker, so I'd like to close it.
