### ISSUE TITLE
 It has been modified to apply the Downgrade Ratio value of sql.

### ISSUE THREAD

**Issue by hahacandy** [opendarkeden/server#45]
[CGAddItemToItemHandler.zip](https://github.com/opendarkeden/server/files/7147237/CGAddItemToItemHandler.zip)

![down](https://user-images.githubusercontent.com/58638224/132937202-e56a7ed0-c0d2-403c-bef5-46e8de8fee67.png)

**Comment by xDezossAx** [comment]
Nice o/
