### ISSUE TITLE
Fixed game freeze when using Sapphire

### ISSUE THREAD

**Issue by hahacandy** [opendarkeden/server#46]
[GCAddItemToItemVerify.zip](https://github.com/opendarkeden/server/files/7147371/GCAddItemToItemVerify.zip)

![Animation](https://user-images.githubusercontent.com/58638224/132939890-698fcd21-3526-49e9-be1d-72a9806fc434.gif)

**Comment by xDezossAx** [comment]
Oh, nice @hahacandy !
