### ISSUE TITLE
Can't move in "Drobeta NW", Can move when a character uses a skill.

### ISSUE THREAD

**Issue by hahacandy** [opendarkeden/server#47]
![Animation](https://user-images.githubusercontent.com/58638224/132956809-b1e0d9c8-ca54-4d36-af3d-0651bfbe7577.gif)

**Comment by xDezossAx** [comment]
only in drobetta nw for you? in mine this is normal at the same coordinates, check if the drobeta_nw.smp and ssi files match their map and .mip, in the ZoneInfo table the ZoneID=32 is with ZoneGroupID='2'?

**Comment by hahacandy** [comment]
@xDezossAx 

may I request the map and mip files?

Everything else seems fine.

**Comment by hahacandy** [comment]
![Animation](https://user-images.githubusercontent.com/58638224/132970747-380fc42f-c051-4dc8-addd-e50b36d0b36b.gif)


Only drobeta_nw does not move.
I'm really sorry but can you share the client file? @xDezossAx

**Comment by hahacandy** [comment]
> ServerID : 1

**Comment by hahacandy** [comment]
i fixed it


vs/conf/gameserver.conf

before
>84    ServerID : 0

after
>84    ServerID : 1


This also fixes errors and displays the server neatly.


![server1](https://user-images.githubusercontent.com/58638224/132972171-55ce8776-0345-4bba-9791-6eac4bd41d3b.png)

![server2](https://user-images.githubusercontent.com/58638224/132972172-1a5e1f80-0eee-4028-95cf-7fa0510ebb95.png)

![server3](https://user-images.githubusercontent.com/58638224/132972174-94ed6849-83de-4822-938b-f43860e2ef91.png)

![Animation](https://user-images.githubusercontent.com/58638224/132972208-99d98234-88d6-4249-8b05-91fa971fd627.gif)

**Comment by xDezossAx** [comment]
when you delete that buggy server, you have to change the same in the .conf ServerID=1 to 0, the strange thing was just that in DrobetaNW for you, or was it all over the map? problem solved o/

**Comment by hahacandy** [comment]
It was only weird in drobeta_nw on server2 when .conf ServerID=1 state.

If I change the .conf ServerID=0 and play the game on server1 it's fine.

it was solved.

**Comment by tiancaiamao** [comment]
@hahacandy    Yes, that's the root cause.
In the past, we can only choose sever group 2, and login to the server group 1 the charactor can not move
See this issue https://github.com/opendarkeden/server/issues/19
