### ISSUE TITLE
Translate Monster Name!

### ISSUE THREAD

**Issue by xDezossAx** [opendarkeden/server#48]
![image](https://user-images.githubusercontent.com/51914495/132962740-60d53304-ca7b-4d9e-bc7e-98481b04cd21.png)

[Monster.cpp.zip](https://github.com/opendarkeden/server/files/7148587/Monster.cpp.zip)

And Update MonsterInfo:

UPDATE MonsterInfo set EName='Chief C Slaughter' WHERE MType='584';
UPDATE MonsterInfo set EName='Quest C Slaughter' WHERE MType='644';
UPDATE MonsterInfo set EName='Boss C Slaughter' WHERE MType='682';
UPDATE MonsterInfo set EName='Dup Gilles de Rais' WHERE MType='721';
UPDATE MonsterInfo set EName='Awak Gilles de Rais' WHERE MType='723';

**Comment by rafakave** [comment]
cool, you could make a [pull request](https://www.dataschool.io/how-to-contribute-on-github/)

**Comment by hahacandy** [comment]
Thank you

**Comment by tiancaiamao** [comment]
The Name length should be less than 20 bytes.

```
mysql> select MType, HName, EName from MonsterInfo where length(HName) >= 20;
Empty set (0.00 sec)

mysql> select MType, HName, EName from MonsterInfo where length(EName) >= 20;
+-------+--------------------+---------------------------+
| MType | HName              | EName                     |
+-------+--------------------+---------------------------+
|   530 | �׸�������ȣ����   | Gregori Guard Shrine      |
|   531 | ��ĥ���Ƽ�ȣ����   | Concilia Guard Shrine     |
|   543 | ��ĥ���Ƽ�������   | Concilia Holy Shrine      |
|   560 | ������ν�����     | Praoroth Guard Shrine     |
|   563 | �̸�Ż��Ƽ����   | Immortality Guard Shrine  |
|   584 | ġ��ũ����������   | Chief Crimson Slaughter   |
|   589 | ġ��ī���������   | Chief Chaos Guardian      |
|   644 | ����Ʈũ���������� | Quest Crimson Slaughter   |
|   682 | ũ���������͸���   | Boss Crimson Slaughter    |
|   721 | ���巹�н�         | Duplicated Gilles de Rais |
|   723 | �������巹         | Awakened Gilles de Rais   |
|   724 | �����̾����ü1    | Vampire Test Model 1      |
|   725 | �����̾����ü2    | Vampire Test Model 2      |
+-------+--------------------+---------------------------+
13 rows in set (0.00 sec)
```

And after changing the EName database, the filename in the `data` dir should also be changed.

**Comment by xDezossAx** [comment]
in case >20, =20 is accepted, I could even edit the server to accept greater than 20, but would I have to edit the hpbar of certain monsters to greater than 120, so as not to pop the correct frame?
