### ISSUE TITLE
MYSQL PROBLEM

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#5]
![image](https://user-images.githubusercontent.com/84734363/121816091-e16c1c80-cc79-11eb-8148-51b67452e4f2.png)
problem load the mysql missing more then 70%  
![image](https://user-images.githubusercontent.com/84734363/121816114-fa74cd80-cc79-11eb-8e4a-68100166dbdf.png)
![image](https://user-images.githubusercontent.com/84734363/121816280-fb5a2f00-cc7a-11eb-85ae-d6e5d2a68d39.png)

**Comment by Supacek** [comment]
FIXED 
![image](https://user-images.githubusercontent.com/84734363/121974203-35acf480-cd7f-11eb-9561-3f776ef24cd6.png)  REPLACE ALL

**Comment by tiancaiamao** [comment]
You have to modify the data or remove `NO_ZERO_DATE` from the `sql_mode`
```
mysql> select @@global.sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@global.sql_mode                                                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

@Supacek
