### ISSUE TITLE
New Skills (equivalent to lvl 161 skills in v6 servers)

### ISSUE THREAD

**Issue by rafakave** [opendarkeden/server#51]
There are some bugs related to the new skills (386~392), but they work to a certain degree.

I'll post here videos of the skills and a pull request soon.

ENCHANTER

https://user-images.githubusercontent.com/16522342/133348468-40dceb0f-f451-4275-917e-19a0348f8c99.mp4

**HEALER**

https://user-images.githubusercontent.com/16522342/133349435-533faf47-f962-4149-82cb-ca010bc8fd11.mp4

**BLADER**

https://user-images.githubusercontent.com/16522342/133349772-7b68c1f2-511b-46c6-8550-a65ed90312ad.mp4

**GUNNER**

https://user-images.githubusercontent.com/16522342/133350031-1868f7e1-08f3-43b0-bf12-7abd812033e2.mp4

**SWORDER**

https://user-images.githubusercontent.com/16522342/133350135-5ebaaf86-028b-4ab7-8490-5648b32d9734.mp4

**VAMPIRES**

https://user-images.githubusercontent.com/16522342/133350330-26d2ab80-3adb-429c-9dfc-2a4ac11fd062.mp4

https://user-images.githubusercontent.com/16522342/133350330-26d2ab80-3adb-429c-9dfc-2a4ac11fd062.mp4

<hr>

### OUSTERS

**COMBAT**

https://user-images.githubusercontent.com/16522342/135539741-b6de7fda-9acd-4524-9697-d712af3f8b35.mp4

**FIRE**

https://user-images.githubusercontent.com/16522342/135539860-6d54a708-2e97-436a-a194-0f80208d17c0.mp4

**EARTH**

https://user-images.githubusercontent.com/16522342/135539887-10edd3a0-d794-4ab9-91a9-f81d17645cee.mp4

**WATER**

https://user-images.githubusercontent.com/16522342/135539907-0605444a-e75d-48f2-9663-0f883d211aa9.mp4

**Comment by rafakave** [comment]
oh, no.
It's the very same client and server you compiled.

I'm just a little slow on it. I was supposed to have sent a pull request days ago.
Basically, it requires those skills to be inserted into SkillBalance table.

**Comment by rafakave** [comment]
Updated video of the skills.

The only problem I found with ousters was that I couldn't learn the skill from the game.

Also, combat skill Penetrate Wheel, must be nerfed.

**Comment by tiancaiamao** [comment]
![image](https://user-images.githubusercontent.com/1420062/200119286-c01faed0-39ae-4dc2-93ef-2b1e4cfda20a.png)

**Comment by tiancaiamao** [comment]
After commit https://github.com/opendarkeden/server/pull/95, those new skills should work

**Comment by Supacek** [comment]
The XRL MISSILE  rly looks like  that ? or it should looks like The Plasma skill lvl 140 ?  i think i remember it was  looking like the plasma from 140.. maybe im wrong

**Comment by rafakave** [comment]
> The XRL MISSILE rly looks like that ? or it should looks like The Plasma skill lvl 140 ? i think i remember it was looking like the plasma from 140.. maybe im wrong

Look like how? Can you post a screenshot?
I know for sure that XRL Missile has a different look than Plasma Rocket (lvl 140 skill). The reason that you may have seen XRL with the same look is because some servers didn't had the sources and used the same visual of Plasma Rocket.
But they are different skills with different visuals.

You can check that on a server like DK Legend, that has both skills with different visuals.

**Comment by Supacek** [comment]
https://user-images.githubusercontent.com/84734363/209997975-dd02347f-7d4b-4665-b7f4-3ddd73906468.mp4

i think the effect is wrong maybe not maybe just missing the  flaying Plazma arrow?

**Comment by tiancaiamao** [comment]
https://github.com/opendarkeden/server/issues/120
I create another issue for it.
