### ISSUE TITLE
Stash Character & StashPet Error

### ISSUE THREAD

**Issue by xDezossAx** [opendarkeden/server#57]
Apparently it loses the item reference (ObjectID), the same happens with the Stash of the Pet

Stash Character
![ItensStash](https://user-images.githubusercontent.com/51914495/134267275-2250a01a-38ae-4360-909d-e58f3b007884.gif)

StashPet

![PetStash](https://user-images.githubusercontent.com/51914495/134267319-c4ba1171-7986-4e4f-82a0-f0a5c99bab06.gif)

**Comment by tiancaiamao** [comment]
Get it. I need some time to investigate this one.

**Comment by tiancaiamao** [comment]
Fixed by https://github.com/opendarkeden/server/pull/59
