### ISSUE TITLE
Character Storage error

### ISSUE THREAD

**Issue by xDezossAx** [opendarkeden/server#61]
Hello, today, check the character storages, I found that the error of disappearing items when you relog still persists, follow the error png...
![npc](https://user-images.githubusercontent.com/51914495/140614024-e3b72650-a836-4bbd-a23f-8e9b3c8d3b01.gif)

**Comment by tiancaiamao** [comment]
OK, it may be similar to  https://github.com/opendarkeden/server/issues/57 but not the same one.
COVID-19 spread here and I'm quarantined by the local policy... without my testing server here. I'll take a look when the quarantine end.

**Comment by xDezossAx** [comment]
ok, thank u @tiancaiamao !

**Comment by NEW-BOY1** [comment]
Stored in the data
But, the client refresh without access to the warehouse items list
Possible, the server can't send warehouse right items list






@tiancaiamao   @xDezossAx

**Comment by xDezossAx** [comment]
I noticed that it gets lost in that, so much so that you can see the items you have stored at the moment, however, if you relog in the server, you lose the reference...
the only certainty I know is that it is an error in the server files, since with the client I used it normally with other binaries.
 @NEW-BOY1

**Comment by xDezossAx** [comment]
Very good @tiancaiamao , I only managed to solve it by returning the GS LS SS folders from the Core, I believe that this way he added the instructions in the loginserver, and sharedserver as well, but this solution is better than repeating that many files o/
