### ISSUE TITLE
hi tiancaiamao

### ISSUE THREAD

**Issue by ErikDARKEDEN** [opendarkeden/server#63]
hi tiancaiamao

Its good that you revived opendarkeden.
this project closed a while after the owner opened a server
it was already 10 years ago i think???

can i contact you?

**Comment by tiancaiamao** [comment]
@ErikDARKEDEN 
It's not the original code like [this one](https://sourceforge.net/projects/opendarkeden/)?

My email is the id tiancaiamao at gmail~
