### ISSUE TITLE
running outside of docker

### ISSUE THREAD

**Issue by de702** [opendarkeden/server#71]
how can i get these files to run outside of docker when i try to start i get this error
using ubuntu 20.04

terminate called after throwing an instance of 'terminate called after throwing an instance of 'UnsupportedErrorUnsupportedError'
'
  what():    what():  std::exception
std::exception

**Comment by tiancaiamao** [comment]
Maybe you don't setup the database correct? What's the full error message?

**Comment by de702** [comment]
you were correct db wasnt setup correctly but now i cant login to server
it only dcs even after editing ip in gameserverinfo in db and configs
this is all i get
<NEW CONNECTION FROM 192.168.0.185:1166
NEW CONNECTION FROM 192.168.0.185:1167
NEW CONNECTION FROM 192.168.0.185:1171
NEW CONNECTION FROM 192.168.0.185:1172

**Comment by tiancaiamao** [comment]
> you were correct db wasnt setup correctly but now i cant login to server it only dcs even after editing ip in gameserverinfo in db and configs this is the error i get NEW CONNECTION FROM 192.168.0.185:1287 NEW CONNECTION FROM 192.168.0.185:1287 RECV PACKET from NONE, CLLogout(154) 11/22
> 
> player status: 1 receive packet: 154 InvalidProtocolException : invalid packet order virtual void LoginPlayer::processCommand(bool)

You're not using the correct client ... (you need to compile this project https://github.com/opendarkeden/client)

**Comment by de702** [comment]
> > you were correct db wasnt setup correctly but now i cant login to server it only dcs even after editing ip in gameserverinfo in db and configs this is the error i get NEW CONNECTION FROM 192.168.0.185:1287 NEW CONNECTION FROM 192.168.0.185:1287 RECV PACKET from NONE, CLLogout(154) 11/22
> > player status: 1 receive packet: 154 InvalidProtocolException : invalid packet order virtual void LoginPlayer::processCommand(bool)
> 
> You're not using the correct client ... (you need to compile this project https://github.com/opendarkeden/client)

that is the client im using, it makes a tt2dk.exe and icon is sapphire from in game
