### ISSUE TITLE
bug when looting 

### ISSUE THREAD

**Issue by de702** [opendarkeden/server#72]
Receive:CGDissectionCorpse(X:106,Y:15,ObjectID:10184)
Receive:CGDissectionCorpse(X:107,Y:16,ObjectID:10185)
Stmt::EQ real Query Error
Stmt [INSERT INTO VampireRingObject (ItemID,  ObjectID, ItemType, OwnerID, Storage, StorageID , X, Y, OptionType, Durability, Grade, ItemFlag) VALUES(10, 10204, 6, '', 5, 1011, 107, 17, '�', 9000, 3, 0)]
Incorrect string value: '\xB8' for column 'OptionType' at row 1
Loading GameWorldInfoManager....

results in dc but can log back in

**Comment by tiancaiamao** [comment]
The panic is from here https://github.com/opendarkeden/server/blob/fb2d2ad1340d6aed0c35e35fe4d5214bc6e34239/src/server/gameserver/item/VampireRing.cpp#L86-L92

Maybe if you change this to something like here, you can workaround the bug https://github.com/opendarkeden/server/blob/fb2d2ad1340d6aed0c35e35fe4d5214bc6e34239/src/server/gameserver/item/VampireRing.cpp#L163-L164


But I haven't  reproduce the bug or verified the changes, you can try yourself.

**Comment by de702** [comment]
> The panic is from here
> 
> https://github.com/opendarkeden/server/blob/fb2d2ad1340d6aed0c35e35fe4d5214bc6e34239/src/server/gameserver/item/VampireRing.cpp#L86-L92
> 
> Maybe if you change this to something like here, you can workaround the bug
> 
> https://github.com/opendarkeden/server/blob/fb2d2ad1340d6aed0c35e35fe4d5214bc6e34239/src/server/gameserver/item/VampireRing.cpp#L163-L164
> 
> But I haven't reproduce the bug or verified the changes, you can try yourself.

its not only vamp rings, vamp necklaces does same thing
Stmt::EQ real Query Error
Stmt [INSERT INTO VampireNecklaceObject (ItemID,  ObjectID, ItemType, OwnerID, Storage, StorageID , X, Y, OptionType, Durability, Grade, ItemFlag) VALUES(6, 12402, 5, '', 5, 61, 98, 200, '�', 6000, 2, 0)]
Incorrect string value: '\xB7' for column 'OptionType' at row 1
