### ISSUE TITLE
gdr lair server crash

### ISSUE THREAD

**Issue by de702** [opendarkeden/server#73]
End state GDRLairIcepole
Start state GDRLairScene1
���巹 ���� 1�� ��
Gilles de Rais�� HP : 40000
Receive:CGMove(X:81,Y:91,Dir:LEFTUP)
Send:284 GCMoveOK(X:80,Y:90,Dir:LEFTUP)
Receive:CGMove(X:80,Y:90,Dir:LEFT)
Send:284 GCMoveOK(X:79,Y:90,Dir:LEFT)
Receive:CGMove(X:79,Y:90,Dir:DOWN)
Send:284 GCMoveOK(X:79,Y:91,Dir:DOWN)
Receive:CGMove(X:79,Y:91,Dir:RIGHTDOWN)
Send:284 GCMoveOK(X:80,Y:92,Dir:RIGHTDOWN)
���巹�� ���մϴ� : ¹Ö²»µÃÍâÃæÕâÃ´àÐÔÓÄØ...ÄãÃÇÊÇ¾­¹ýÄÇÐ©¿ÉÅÂµÄÏÝÚå²ÅÀ´µ½ÕâÀïµÄÂð£¿
Send:246 GCGlobalChat(Color:16777215,Message:���巹 ¹Ö²»µÃÍâÃæÕâÃ´àÐÔÓÄØ...ÄãÃÇÊÇ¾­¹ýÄÇÐ©¿ÉÅÂµÄÏÝÚå²ÅÀ´µ½ÕâÀïµÄÂð£¿,Race:1)
Receive:CGSay(Color:0, Message:*bug_report too large PacketSize ID)246 136/134)
���巹�� ���մϴ� : ÇëÄãÃÇ²»ÒªÎó»á£¬ÕâÀïËäÈ»ÊÇÎÒµÄ°²Éí´¦£¬²»¹ýÎÒÒ²²»Çå³þÄÇÐ©ÏÝÚåµÄÓÉÀ´¡£
==============================================================================
UNHANDLED EXCEPTION OCCURED
==============================================================================

**Comment by tiancaiamao** [comment]
gdr lair... I didn't test it, so I'm not sure what happened.
Is there any more detailed log about the "UNHANDLED EXCEPTION OCCURED" ?

**Comment by de702** [comment]
gdr crash is from lines gsstring

INSERT INTO `GSStringPool` VALUES ('330', 'This feature is not supported yet.');
INSERT INTO `GSStringPool` VALUES ('331', 'No wonder it\'s so noisy outside?? Did you get through those horrible traps to arrive here?');
INSERT INTO `GSStringPool` VALUES ('332', 'Please don\'t be mistaken. Although I have settled here, I\'m not clear the origin of those traps.');
INSERT INTO `GSStringPool` VALUES ('333', 'I\'m also obssessed by the traps?? it\'s a mystery who created them.');
INSERT INTO `GSStringPool` VALUES ('334', 'Wait, there must be something to appear. Is it you guys who do this? Do you guys want to hurt me?');
INSERT INTO `GSStringPool` VALUES ('335', 'Don\'t you do that? Anyway, you are all strong warriors.');
INSERT INTO `GSStringPool` VALUES ('336', 'You guys make me think about a girl named Jendaluke');
INSERT INTO `GSStringPool` VALUES ('337', 'Her power is the greatest. I was getting to respect her when she visited me for saving her nation.');
INSERT INTO `GSStringPool` VALUES ('338', 'She is so young to be here for saving the nation.');
INSERT INTO `GSStringPool` VALUES ('339', 'Why are you guys visiting me? You should know that it\'s very dangerous here.');
INSERT INTO `GSStringPool` VALUES ('340', 'Now I\'m so headache that I cannot help you for the moment.');
INSERT INTO `GSStringPool` VALUES ('341', 'Well, you should not have ejected these guests who were asking for help. It\'s so rude.');
INSERT INTO `GSStringPool` VALUES ('342', 'Please don\'t blame me. The old make such mistakes sometimes. After a while, watch the ballon go up,hahaha!');
INSERT INTO `GSStringPool` VALUES ('343', 'Great, wonderful! Let me see.');
INSERT INTO `GSStringPool` VALUES ('344', 'I really cannot stand the fragrance from your guys.');
INSERT INTO `GSStringPool` VALUES ('345', 'It\'s a humiliation that I\'m defeated by you guys.');
INSERT INTO `GSStringPool` VALUES ('346', 'It\'s dangerous here. Get out of here?? Oh, I can\'t hold on.');
INSERT INTO `GSStringPool` VALUES ('347', 'Well! I felt so bad?? You guys\' expressions are so ridiculous. I\'d like to play more tricks on you more.');
INSERT INTO `GSStringPool` VALUES ('348', 'Stop! Stop attack! I didn\'t mean to. Well?? I thought everything was well, but evilness still exists, cannot get rid of.');
INSERT INTO `GSStringPool` VALUES ('349', 'Things which have happened cannot be redeemed. Do you want to make a compromise with me now ?');
INSERT INTO `GSStringPool` VALUES ('350', 'The power which Jendaluke wanted to have?? Don\'t you want to know? ');
INSERT INTO `GSStringPool` VALUES ('351', 'Then, Jendaluke refused my request. However, I believe you will not absolutely.');
INSERT INTO `GSStringPool` VALUES ('352', 'Then, I gave her the power she wanted at the expense of her flesh and blood. I don\'t think the requirement is high.');
INSERT INTO `GSStringPool` VALUES ('353', 'I was hurt badly so I decided to cut off all connections with outside. That\'s why I designed all of these traps.');
INSERT INTO `GSStringPool` VALUES ('354', 'I abandoned all my own glories!');
INSERT INTO `GSStringPool` VALUES ('355', 'Look! I created lives with my power. You all can get renascence.');
INSERT INTO `GSStringPool` VALUES ('356', 'Ah? What\'s wrong? Is it not enough? If no human child\'s blood, perfect life cannot be created!');
INSERT INTO `GSStringPool` VALUES ('357', 'Once we had Jendaluke\'s blood?? By the way, try some of your blood, although it\'s not that pure.');
INSERT INTO `GSStringPool` VALUES ('358', 'I will creat perfect life. Your blood is flowing in my body, you guys should be feel proud.');
INSERT INTO `GSStringPool` VALUES ('359', 'The blood of like you guys??. You don\'t need to feel sorry. I\'ll take care of everything. ');
INSERT INTO `GSStringPool` VALUES ('360', 'I really don\'t understand, why are you feeling so hopeful for life? Anyway, everybody will die, turning to dust');
INSERT INTO `GSStringPool` VALUES ('361', 'Ask her who she is.');
INSERT INTO `GSStringPool` VALUES ('362', 'You\'d better go back. It\'s good for you.');
INSERT INTO `GSStringPool` VALUES ('363', 'I warned you, it\'s a dangerous place. Now, I\'m?? Ah??');
INSERT INTO `GSStringPool` VALUES ('364', 'Ahaha, the shell is finally removed.');
INSERT INTO `GSStringPool` VALUES ('365', 'Magic was used for bringing you memorable things. But now, it seems no useful.');
INSERT INTO `GSStringPool` VALUES ('366', 'Have you guys ever seen that? This is a real masterwork. Look at yourselves who are fighting with illusions, so poor.');
INSERT INTO `GSStringPool` VALUES ('367', 'How\'s your feeling? Is it great to be tricked?');
INSERT INTO `GSStringPool` VALUES ('368', 'No, please, please let me go!');
INSERT INTO `GSStringPool` VALUES ('369', 'From now on, nothing is illusion.');
INSERT INTO `GSStringPool` VALUES ('370', 'OK, follow me!');
INSERT INTO `GSStringPool` VALUES ('371', 'I\'m tired of people who play double characters or things like just waiting for food.');
