### ISSUE TITLE
dc when joining party

### ISSUE THREAD

**Issue by de702** [opendarkeden/server#75]
Receive:CGVerifyTime()
Receive:CGPartyInvite(TargetObjectID : 10291,CODE : 2)
Send:304 GCPartyJoined(MemberCount:2,(·è¿ñ),(soup),)
Send:304 GCPartyJoined(MemberCount:2,(·è¿ñ),(soup),)
▒̺▒Ʈ ▒▒Ƽ▒▒ ▒Ἲ▒Ǿ▒▒ϴ▒. : ·è¿ñ
Receive:CGSay(Color:0, Message:*bug_report Exceed PacketID:28789)
Send:305 GCPartyLeave(Expeller:Expellee:·è¿ñ)
Send:305 GCPartyLeave(Expeller:Expellee:·è¿ñ)
void Party::eventPartyCrash()
▒̺▒Ʈ ▒▒Ƽ▒▒ ▒▒▒▒▒ϴ▒. : ·è¿ñ
▒̺▒Ʈ ▒▒Ƽ▒▒ ▒▒▒▒▒ϴ▒. : soup
Receive:CGSay(Color:0, Message:*bug_report Exceed PacketID:28789)

**Comment by tiancaiamao** [comment]
Thanks for your report @de702

**Comment by tiancaiamao** [comment]
It seems to panic in this function https://github.com/opendarkeden/client/blob/9ed166a29126d85e2676bd7609fb46e4bff06346/Client/Packet/Gpackets/GCPartyJoinedHandler.cpp#L29

I can see the previous packet receive log ... until here.

**Comment by tiancaiamao** [comment]
@de702 the party join issue is solved~

**Comment by Supacek** [comment]
i still have this issue just dc no any error ? :/
