### ISSUE TITLE
advanceclass exp does not update

### ISSUE THREAD

**Issue by de702** [opendarkeden/server#76]
no error just bug exp does update till after changing maps, will remain at same number and percent

**Comment by tiancaiamao** [comment]
Maybe it's by design, or maybe caused by the client, but I should take a look before getting the conclusion.

**Comment by de702** [comment]
how do you go about addressing problems? i would like to try and help but i dont know a whole lot, how do you identify which files is the problem or which files does what?

**Comment by tiancaiamao** [comment]
> how do you go about addressing problems? i would like to try and help but i dont know a whole lot, how do you identify which files is the problem or which files does what?

I need a weekend for it.
Last few days, my wife give birth to our first baby, so I spent the time in the hospital.
A lot of working things of my job lag... so I can't handle this issue in time

**Comment by hahacandy** [comment]
> > 문제를 해결하는 방법은 무엇입니까? 도움을 주고 싶지만 많이 알지 못합니다. 어떤 파일이 문제인지 또는 어떤 파일이 어떤 역할을 하는지 어떻게 식별합니까?
> 
> 주말이 필요해요. 지난 며칠간 아내가 첫 아이를 낳아 병원에서 시간을 보냈다. 내 작업의 많은 작업 지연 ... 그래서 나는이 문제를 제 시간에 처리 할 수 ​​​​없습니다

congratulations on having a baby
