### ISSUE TITLE
another error in makefile

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#8]
hallo thanx for fix but got another problem..
![image](https://user-images.githubusercontent.com/84734363/123240121-504e3e80-d4e0-11eb-8a10-42f556e33bd9.png)
![image](https://user-images.githubusercontent.com/84734363/123240336-84296400-d4e0-11eb-802f-9bb10c79d9f5.png)

**Comment by Supacek** [comment]
fixed its default  path is 
![image](https://user-images.githubusercontent.com/84734363/123242602-7ecd1900-d4e2-11eb-81d5-8ebfd8e377c3.png)

**Comment by tiancaiamao** [comment]
If you install the mysql using those command on ubuntu:

```
sudo apt install libmysqlclient-dev
sudo apt install mysql-server
```

This should be the default path.
