### ISSUE TITLE
luaError.log 

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#85]
![image](https://user-images.githubusercontent.com/84734363/195202972-f2a89d5a-5a00-46fa-8f16-4e12949274bc.png)

have some errors in lua Error but idk what causing this error :/ can i have more infos any way?

**Comment by Supacek** [comment]
i think theres mising folder with lua scripts

**Comment by tiancaiamao** [comment]
What's action that trigger this error?

**Comment by Supacek** [comment]
starting server. also there should be treasure folder probly  i think the error dissapierd i add the lua folder from other server theres scripts for xmas event or somethink idk didnt test it yet

**Comment by Supacek** [comment]
also there is some files that should be in /data/treasure/  folder   but u have them only in   /data/   im not sure ill test it later

**Comment by Supacek** [comment]
here it is but  get some errors 
![image](https://user-images.githubusercontent.com/84734363/195731635-78ae68f9-2cae-4a1f-8ab1-920ca1b8b8de.png)

**Comment by tiancaiamao** [comment]
I guess you're using some other server data files mixed with this one.
There is no `/data/treasure/` folder for this server. @Supacek

**Comment by Supacek** [comment]
i know but the lua folder should be there the reasure folder im testing

**Comment by xDezossAx** [comment]
Execute ./luaAllCompile for recompiler .lua files.

**Comment by tiancaiamao** [comment]
Different version comes with different `data` files and `sql database`, they can't be used together.

Now I found that the current database referencing some lua files, which doesn't exit :-(

**Comment by xDezossAx** [comment]
> Different version comes with different `data` files and `sql database`, they can't be used together.
> 
> Now I found that the current database referencing some lua files, which doesn't exit :-(

The files are lua are referenced in the Triggers table, related to gaining Christmas items and new characters I believe,
but with the instruction I explained in the other thread, it works without returning error.

[https://github.com/opendarkeden/server/issues/93#issuecomment-1304505823](url)
