### ISSUE TITLE
Server End problem

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#86]
While server is running like 12h  and i come back from work ill try to log in and i get DC  today i get  DBerror.log

![image](https://user-images.githubusercontent.com/84734363/195708486-e56d2f88-8a11-409e-914e-071ea4144012.png)

any  idea why  is server shuting down ???

**Comment by NEW-BOY1** [comment]
I think you need it

show global variables like '%wait_timeout';

When you don't have connection after a certain period of time. Mysql will lose it

**Comment by Supacek** [comment]
> I think you need it
> 
> show global variables like '%wait_timeout';
> 
> When you don't have connection after a certain period of time. Mysql will lose it

so today same problem .i get home try to login server boom 
![image](https://user-images.githubusercontent.com/84734363/195940021-3564ad45-9a3d-4ddd-96f3-7593b0522a8b.png)
this happened 

last log in loginserver is  

Stmt [INSERT INTO LoginPlayerData (PlayerID,IP,Date,Time) VALUES ('admin','xxxxmyipadressxxxxx','2022-10-14','22:40:09')]
Lost connection to MySQL server during query

![image](https://user-images.githubusercontent.com/84734363/195940409-eb3395e4-5fe1-4976-8393-0385f2994107.png)

**Comment by Supacek** [comment]
the server is running empty no one is online so thats the probmel maybe so i need change that time probly right ?

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/195944036-1559c138-4f8c-4d4f-a72a-0b270fdadaab.png)

**Comment by NEW-BOY1** [comment]
> ![图片](https://user-images.githubusercontent.com/84734363/195944036-1559c138-4f8c-4d4f-a72a-0b270fdadaab.png)


It has told you, lost the connection  mysql

wait_timeout=2880000
interactive_timeout = 2880000
You could be longer this time

**Comment by Supacek** [comment]
> > ![图片](https://user-images.githubusercontent.com/84734363/195944036-1559c138-4f8c-4d4f-a72a-0b270fdadaab.png)
> 
> It has told you, lost the connection mysql
> 
> wait_timeout=2880000 interactive_timeout = 2880000 You could be longer this time

ill try

**Comment by tiancaiamao** [comment]
@NEW-BOY1 is right.
The MySQL settings may cause inactive connection been kicked out, you need to change some configuration or global variables. @Supacek

**Comment by Supacek** [comment]
Fixed put times inzo mysql conf file..

**Comment by Supacek** [comment]
[mysqld]
wait_timeout=2880000
interactive_timeout = 2880000

put it in mysql.cnf

**Comment by Supacek** [comment]
closed fixed
