### ISSUE TITLE
Connect to sharedserver fail

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#87]
![image](https://user-images.githubusercontent.com/84734363/195710960-0eaf00da-d8a0-44dd-a890-87607fdb56ad.png)

while im using  this 
![image](https://user-images.githubusercontent.com/84734363/195711002-01a552cc-304d-4e17-be11-7d16e194053c.png)
i have connec to shared server fail but if im using script  for start theres no problem anyone know why?

![image](https://user-images.githubusercontent.com/84734363/195711057-915d39e7-0286-46e6-a710-1012d2ad5498.png)

**Comment by tiancaiamao** [comment]
Seems you're not using docker, so you need to modify the IP address of the config file to your own IP @Supacek 

The config files for docker env https://github.com/opendarkeden/server/tree/master/docker/conf
And the config files if you deploy on a native linux env https://github.com/opendarkeden/server/tree/master/conf
