### ISSUE TITLE
Creating Account

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#88]
`INSERT` INTO Player (PlayerID,Password,Access) VALUE ('username',PASSWORD('password'), 'ALLOW')
> 1406 - Data too long for column 'Password' at row 1
> Time: `0.054s`
 ok so we have problem  or i have problem
 the new hash code is to logn so we need to change table  PLAYER 
 
![image](https://user-images.githubusercontent.com/84734363/197364440-1746f978-ba31-48b5-a67d-cdf93cdf0489.png)
and set  Lenght from  15 to like 50 cuz the new hash is 41 lenght long 

then try again create account with query
![image](https://user-images.githubusercontent.com/84734363/197364552-9944eeca-d7bf-4171-9697-960572a5597d.png)

succes 
![image](https://user-images.githubusercontent.com/84734363/197364560-dc1092a7-e8ad-4e51-bbff-7d39fc7c58bf.png)

but the problem is after trying log in into game  Error
![image](https://user-images.githubusercontent.com/84734363/197364571-c615f504-47fd-41de-93e9-297efada558e.png)

the problem must be in the new hash 
any help ?  how i can figure it out ???
when i try to use 
query   with  INSERT` INTO Player (PlayerID,Password,Access) VALUE ('username',**OLD_PASSWORD**('password'), 'ALLOW')
function dont exist 

any idea? how to fix ?

**Comment by Supacek** [comment]
INTO Player (PlayerID,Password,Access) VALUE ('username',PASSWORD('password'), 'ALLOW') 

possible fix use only 
INTO Player (PlayerID,Password,Access) VALUE ('username', 'password', 'ALLOW')  =  no hash password

**Comment by tiancaiamao** [comment]
Yes, I changed code ... to use the raw passward.
You can  `INTO Player (PlayerID,Password,Access) VALUE ('username','your password'), 'ALLOW')`

@Supacek

**Comment by tiancaiamao** [comment]
No `PASSWORD` or `OLD_PASSWORD` function

**Comment by Supacek** [comment]
Fixed ye
