### ISSUE TITLE
server stop or restard?

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#9]
any way to do this? server stop or restart shared or login or gameserver

**Comment by tiancaiamao** [comment]
You have to write some script yourself...
The server is still not quite stable, usually I run those commands one by one:

```
./bin/loginserver -f ./conf/loginserver.conf
./bin/sharedserver -f ./conf/sharedserver.conf
./bin/gameserver -f ./conf/gameserver.conf
```
