### ISSUE TITLE
TAME Wolf 

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#90]
Receive:CGTameMonster(ObjectID :11930)   Thats all i get nothink in inventory no working   Taming pet no work...

**Comment by de702** [comment]
> Receive:CGTameMonster(ObjectID :11930) Thats all i get nothink in inventory no working Taming pet no work...

works fine might need to adjust tame ratio in db in food table

**Comment by tiancaiamao** [comment]
My feedback is that it's difficult to find a dog in the map, but taming actually works well

**Comment by de702** [comment]
> My feedback is that it's difficult to find a dog in the map, but taming actually works well

you just need to summon them, or add more via summons in zoneinfo in db, you can also make them spawn in specfic x/y on map via summons in zoneinfo

dog id is 687

**Comment by Supacek** [comment]
yo that was my bad i remove the Original number from Tab 
![image](https://user-images.githubusercontent.com/84734363/199114025-50f0e58e-3ab1-4429-8509-fee29ff75b23.png)
