### ISSUE TITLE
Skill FireMeteor and  SacredStamp mismatch between client and server

### ISSUE THREAD

**Issue by tiancaiamao** [opendarkeden/server#96]
On the server side, FireMeteor and  SacredStamp cast to object .. cast to tile would result in error
While on the client side, FireMeteor and  SacredStamp cast to tile, they cause range damage.

**Comment by Supacek** [comment]
and what should be correct? cast on object or tile ? or what we need to fix ? i dont know these spells

**Comment by tiancaiamao** [comment]
Either change the client side, or the server side.

https://user-images.githubusercontent.com/16522342/135539860-6d54a708-2e97-436a-a194-0f80208d17c0.mp4

You see this one? if you click on the ground instead of on a monster, this skill still spell.
But the server always send a GCSkillFail packet ... no damage...

I'm not sure the settings of the other servers, maybe follow the client's behaviour is better: make it `SimpleTileMissileSkill` instead of `SimpleMissileSkill` like here https://github.com/opendarkeden/server/blob/79f368d9bd69ed0789f1a41ea88bd5481afdb8a7/src/server/gameserver/skill/SacredStamp.cpp#L48

**Comment by Supacek** [comment]
i think voth should be working and its aoe skill probly  right?

**Comment by tiancaiamao** [comment]
> i think both should be working and its aoe skill probly right?

Yes
