### ISSUE TITLE
Create Guild

### ISSUE THREAD

**Issue by Supacek** [opendarkeden/server#97]
yo guys is Create guild working   i dont think so  its not seen ingame  did someone test it ?

**Comment by xDezossAx** [comment]
![image](https://user-images.githubusercontent.com/51914495/200197235-87630ac6-dcc2-4add-a82d-668bbdd000b6.png)
Here there was an error when creating, the sharedserver crashed.

**Comment by Supacek** [comment]
Wrong Query there isnt 'intro' default in database table  GuildMembers  so i set it to  0 default but after that no error the database is working im member of the guild now but still dont see it in guild list or cannot open anythink :/

**Comment by xDezossAx** [comment]
> Wrong Query there isnt 'intro' default in database table GuildMembers so i set it to 0 default but after that no error the database is working im member of the guild now but still dont see it in guild list or cannot open anythink :/

I also changed the Intro column to accept null, but even though I am Guild Leader and member, I can't see it.

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/200414902-0d230fb2-7da1-4c80-8a1c-6a0be88b7b89.png)
  didnt find anythink else i dont know wheres problem :/

**Comment by xDezossAx** [comment]
I did a test on other files, and it returns the following when creating a guild:

_Receive:CGRegistGuild(GuildName:BYEBYEGuildIntro:WELCOME TO THE JUNGLE)
Receive:GSAddGuild (GuildName:BYEBYE
GuildMaster:▒▒▒▒▒▒▒▒
GuildIntro:WELCOME TO THE JUNGLE
GuildState:1
GuildRace:0ServerGroupID:0 )
Receive:SGAddGuildOK(
GuildID:25580
GuildName:BYEBYE
GuildRace:0
GuildState:1
GuildZoneID:16052
GuildMaster:▒▒▒▒▒▒▒▒
GuildIntro:WELCOME TO THE JUNGLE)
Receive:SGAddGuildMemberOK(
GuildID:25580Name:▒▒▒▒▒▒▒▒
GuildMemberRank:1)
Receive:CGVerifyTime()_

and returns this when I enter the guild wait list

_Receive:CGSelectGuild(GuildID:25580)_

I think it has something to do with the file: SGAddGuildOK.* '-'

**Comment by xDezossAx** [comment]
in SGAddGuildOK.cpp exist this line "#ifdef __GAME_SERVER__" if you comment her should work
void SGAddGuildOK::execute (Player * pPlayer ) 
{

//#ifdef __GAME_SERVER__

	__BEGIN_TRY
		
	SGAddGuildOKHandler::execute(this);
		
	__END_CATCH

//#endif
}

the same should do with the SGAddGuildMemberOK, I'm going to sleep now later test

**Comment by Supacek** [comment]
i dont have time now to try im sorry  maybe tomorrow

**Comment by xDezossAx** [comment]
in the makefile you have to reference it when creating the libsharedserverpackets.a, when i get home i will test.

**Comment by Supacek** [comment]
> in the makefile you have to reference it when creating the libsharedserverpackets.a, when i get home i will test.

did u test it is it working ?

**Comment by xDezossAx** [comment]
@Supacek These are the same files here, only with the Cpackets, Gpackets, Lpackets, Spackets folders restored, just send the make depall command and then run make in this version you will see that the GuildWait List and Guild List work normally. you can have a base to adjust this without the respective folders. also tests the "Recall Motorcycle problem" 
[src.zip](https://github.com/opendarkeden/server/files/9986290/src.zip)
[GuildInfo.zip](https://github.com/opendarkeden/server/files/9986291/GuildInfo.zip)

**Comment by Supacek** [comment]
> 

im so glad u trying help but i dont like those files theres so many copy files some of them are like 5x same i dont know this type of src can u please like try to stay with the same files and help me  what to do ? sorry my english still sux.,.

**Comment by Supacek** [comment]
im trying scan the files what we have but it looks same the problem is only maybe in the make file ?

**Comment by xDezossAx** [comment]
@Supacek these zip files is the same here, but with the restored folders, you can get what works in this base to correct the files here, the inclusion of files changes in the compiled librarys. I took advantage of the makefile of other files in these files here from opendarkeden :)

**Comment by xDezossAx** [comment]
there must be somewhere, where I inform the GCActiveGuildList and GCWaitGuildList, but I haven't had time to tinker with it yet.

**Comment by Supacek** [comment]
is it working with the same client and the server core?

**Comment by xDezossAx** [comment]
> is it working with the same client and the server core?

yes, same cliente same files 👍

**Comment by Supacek** [comment]
i scan the files and theres nothing it must by another files

**Comment by Supacek** [comment]
Cant even Quit Guild  
![image](https://user-images.githubusercontent.com/84734363/201431633-7d2725d0-b799-40c6-8c39-6ec5971ab24a.png)

**Comment by Supacek** [comment]
still didnt figure it out im done lol :/

**Comment by NEW-BOY1** [comment]
When you create. Need your 5 friends support. To be successful

**Comment by Supacek** [comment]
> When you create guild . Need your 5 friends support. To be successful

the guild is created  in database but didnt opening in game

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/201725167-64a1f39b-66eb-4f8d-a910-2a35b4410ed9.png)
no Guild

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/201725196-f3c8ca06-f446-43a4-be56-376f536a2209.png)

**Comment by Supacek** [comment]
cant even open Clan info nothink
![image](https://user-images.githubusercontent.com/84734363/201725502-97c9e0fb-4cdd-47e3-9d80-e6c8dbb1e3b4.png)

**Comment by NEW-BOY1** [comment]
You may try the game created within the guild

**Comment by Supacek** [comment]
> > is it working with the same client and the server core?
> 
> yes, same cliente same files 👍 , I'll try to adjust it at home without needing the folders again, but this one is good for testing bugs, it could also be something related to the CGRequestGuild

hallo, did u trz it without the files ? i need telp to figure out this the Guild is importent for me..

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/202005011-2583c565-883f-4a85-8ef6-6eba404bf0a0.png)
Like i dont even get those messages about u
![image](https://user-images.githubusercontent.com/84734363/202005063-85c21122-172f-4eba-bde7-885aa4db28d8.png)
or 
![image](https://user-images.githubusercontent.com/84734363/202005104-7865db28-2618-4fba-a974-661e61976dc3.png)

**Comment by Supacek** [comment]
![image](https://user-images.githubusercontent.com/84734363/202589444-e719e83b-9249-4b6c-89a5-fa7e3a1a466d.png)
SGGuildInfo.cpp  commend  it 

//////////////////////////////////////////////////////////////////////
// execute packet's handler
//////////////////////////////////////////////////////////////////////
void SGGuildInfo::execute (Player * pPlayer ) 
{

//#ifdef __GAME_SERVER__

	__BEGIN_TRY
		
	SGGuildInfoHandler::execute(this);
		
	__END_CATCH

//#endif
}

FIXED !!!

**Comment by Supacek** [comment]
its not working did u test it ? it create guild after restart but its not working normaly theres no message nothink

**Comment by tiancaiamao** [comment]
> its not working did u test it ? it create guild after restart but its not working normaly theres no message nothink

Are you using the latest version? I've tested it and it should have been fixed.
